version: '2'
services:
    minitwitter-app:
        image: minitwitter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://minitwitter-mysql:3306/minitwitter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    minitwitter-mysql:
        extends:
            file: mysql.yml
            service: minitwitter-mysql
